# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.SmallIntegerField(verbose_name='Oocytes received (ml)')),
                ('transferred', models.SmallIntegerField(verbose_name='Oocytes transferred (ml)')),
                ('used', models.SmallIntegerField(verbose_name='Oocytes used (ml)')),
                ('expt_from', models.DateField(verbose_name='Experiments from')),
                ('expt_to', models.DateField(verbose_name='Experiments to')),
                ('expt_location', models.CharField(max_length=80, verbose_name='Experiment location')),
                ('expt_disposed', models.BooleanField(verbose_name='Disposed')),
                ('disposal_sentby', models.CharField(max_length=30, verbose_name='Disposal sent by initials')),
                ('disposal_date', models.DateField(verbose_name='Disposal date')),
                ('waste_type', models.CharField(choices=[('solid', 'Solid'), ('liquid', 'Liquid')], max_length=30, verbose_name='Type of waste')),
                ('waste_content', models.CharField(max_length=30, verbose_name='Waste content')),
                ('waste_qty', models.SmallIntegerField(verbose_name='Waste quantity')),
                ('autoclave_indicator', models.BooleanField(verbose_name='Autoclave indicator')),
                ('autoclave_complete', models.BooleanField(verbose_name='Autoclave complete')),
            ],
        ),
        migrations.CreateModel(
            name='Frog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frogid', models.CharField(max_length=30, unique=True, verbose_name='Frog ID')),
                ('tankid', models.IntegerField(default=0, verbose_name='Tank ID')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10, verbose_name='Gender')),
                ('species', models.CharField(choices=[('x.borealis', 'X.borealis'), ('x.laevis', 'X.laevis')], max_length=30, verbose_name='Species')),
                ('current_location', models.CharField(choices=[('stored_aibn', 'Stored at AIBN Animal House'), ('disposed_aibn', 'Disposed of at AIBN Animal House'), ('disposed_oh', 'Disposed of at Otto Hirschfeld Animal House')], max_length=80, verbose_name='Current Location')),
                ('condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Oocyte Health Condition')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='General Remarks')),
                ('aec', models.CharField(blank=True, max_length=80, null=True, verbose_name='AEC')),
                ('death', models.CharField(blank=True, choices=[('culled', 'Culled'), ('found', 'Found dead'), ('alive', 'Not dead')], max_length=10, null=True, verbose_name='Type of Death')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Date of Death')),
                ('death_initials', models.CharField(blank=True, max_length=10, null=True, verbose_name='Initials')),
                ('disposed', models.BooleanField(default=False, verbose_name='Disposed')),
                ('autoclave_date', models.DateField(blank=True, null=True, verbose_name='Autoclave Date')),
                ('autoclave_run', models.IntegerField(blank=True, default=0, null=True, verbose_name='Autoclave Run')),
                ('incineration_date', models.DateField(blank=True, null=True, verbose_name='Incineration Date')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opnum', models.IntegerField(default=1, verbose_name='Operation Number')),
                ('opdate', models.DateField(verbose_name='Operation Date')),
                ('anesthetic', models.CharField(max_length=30, verbose_name='Anesthetic')),
                ('volume', models.SmallIntegerField(verbose_name='Volume (ml)')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('initials', models.CharField(max_length=10, verbose_name='Operated by')),
                ('frogid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Frog')),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qen', models.CharField(max_length=20, unique=True, verbose_name='QEN')),
                ('arrival_date', models.DateField(verbose_name='Arrival date')),
                ('aqis', models.CharField(max_length=20, verbose_name='AQIS')),
                ('females', models.IntegerField(default=0, verbose_name='Females')),
                ('males', models.IntegerField(default=0, verbose_name='Males')),
                ('species', models.CharField(choices=[('x.borealis', 'X.borealis'), ('x.laevis', 'X.laevis')], max_length=30, verbose_name='Species')),
                ('supplier', models.CharField(choices=[('nasco', 'NASCO'), ('xenopus', 'Xenopus One'), ('uq', 'UQ')], max_length=30, verbose_name='Supplier')),
                ('country', models.CharField(choices=[('usa', 'USA'), ('australia', 'Australia')], max_length=30, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Qap',
            fields=[
                ('qap', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='QAP')),
                ('building', models.CharField(max_length=60, verbose_name='Building')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.SmallIntegerField(verbose_name='Volume carried (ml)')),
                ('transfer_date', models.DateField(verbose_name='Transfer date')),
                ('transporter', models.CharField(max_length=120, verbose_name='Transporter Name or Initials')),
                ('method', models.CharField(max_length=120, verbose_name='Method')),
                ('operationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Operation', verbose_name='Operation')),
            ],
        ),
        migrations.CreateModel(
            name='TransferApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop', models.CharField(max_length=100, verbose_name='SOP details')),
                ('tfr_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfr_from', to='frogs.Qap', verbose_name='Transfer from')),
                ('tfr_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfr_to', to='frogs.Qap', verbose_name='Transfer to')),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='transferapproval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.TransferApproval', verbose_name='Transfer from/to'),
        ),
        migrations.AddField(
            model_name='frog',
            name='qen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Permit'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='transferid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Transfer'),
        ),
    ]
