# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('code', models.CharField(max_length=5, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Deathtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Death Type')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.PositiveSmallIntegerField(verbose_name='Oocytes received (ml)')),
                ('transferred', models.PositiveSmallIntegerField(verbose_name='Oocytes transferred (ml)')),
                ('used', models.PositiveSmallIntegerField(verbose_name='Oocytes used (ml)')),
                ('expt_from', models.DateField(verbose_name='Experiments from')),
                ('expt_to', models.DateField(verbose_name='Experiments to')),
                ('expt_disposed', models.BooleanField(default=False, verbose_name='Disposed')),
                ('disposal_sentby', models.CharField(blank=True, max_length=30, null=True, verbose_name='Disposal sent by initials')),
                ('disposal_date', models.DateField(blank=True, null=True, verbose_name='Disposal date')),
                ('waste_content', models.CharField(blank=True, max_length=30, null=True, verbose_name='Waste content')),
                ('waste_qty', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Waste quantity')),
                ('autoclave_indicator', models.BooleanField(default=False, verbose_name='Autoclave indicator')),
                ('autoclave_complete', models.BooleanField(default=False, verbose_name='Autoclave complete')),
            ],
        ),
        migrations.CreateModel(
            name='Frog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frogid', models.CharField(max_length=30, unique=True, verbose_name='Frog ID')),
                ('tankid', models.PositiveSmallIntegerField(default=0, verbose_name='Tank ID')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10, verbose_name='Gender')),
                ('condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Oocyte Health Condition')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='General Remarks')),
                ('aec', models.CharField(blank=True, max_length=80, null=True, verbose_name='AEC')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Date of Death')),
                ('death_initials', models.CharField(blank=True, max_length=10, null=True, verbose_name='Initials')),
                ('disposed', models.BooleanField(default=False, verbose_name='Disposed')),
                ('autoclave_date', models.DateField(blank=True, null=True, verbose_name='Autoclave Date')),
                ('autoclave_run', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Autoclave Run')),
                ('incineration_date', models.DateField(blank=True, null=True, verbose_name='Incineration Date')),
            ],
        ),
        migrations.CreateModel(
            name='FrogAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('frogid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Frog')),
            ],
        ),
        migrations.CreateModel(
            name='Imagetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Image Type')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Current Location')),
                ('brief', models.CharField(max_length=20, verbose_name='Abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opnum', models.PositiveSmallIntegerField(default=1, verbose_name='Operation Number')),
                ('opdate', models.DateField(verbose_name='Operation Date')),
                ('anesthetic', models.CharField(max_length=30, verbose_name='Anesthetic')),
                ('volume', models.PositiveSmallIntegerField(verbose_name='Volume (ml)')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('initials', models.CharField(max_length=10, verbose_name='Operated by')),
                ('frogid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Frog')),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqis', models.CharField(max_length=20, verbose_name='AQIS')),
                ('qen', models.CharField(max_length=20, unique=True, verbose_name='QEN')),
                ('females', models.PositiveSmallIntegerField(default=0, verbose_name='Females')),
                ('males', models.PositiveSmallIntegerField(default=0, verbose_name='Males')),
                ('arrival_date', models.DateField(verbose_name='Arrival date')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Country', verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Qap',
            fields=[
                ('qap', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='QAP')),
                ('building', models.CharField(max_length=60, verbose_name='Building')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Species')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveSmallIntegerField(verbose_name='Volume carried (ml)')),
                ('transfer_date', models.DateField(verbose_name='Transfer date')),
                ('transporter', models.CharField(max_length=120, verbose_name='Transporter Name or Initials')),
                ('method', models.CharField(max_length=120, verbose_name='Method')),
                ('operationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Operation', verbose_name='Operation')),
            ],
        ),
        migrations.CreateModel(
            name='TransferApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop', models.CharField(max_length=100, verbose_name='SOP details')),
                ('tfr_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfr_from', to='frogs.Qap', verbose_name='Transfer from')),
                ('tfr_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfr_to', to='frogs.Qap', verbose_name='Transfer to')),
            ],
        ),
        migrations.CreateModel(
            name='Wastetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Waste Type')),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='transferapproval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.TransferApproval', verbose_name='Transfer from/to'),
        ),
        migrations.AddField(
            model_name='permit',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Species', verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='permit',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='frogattachment',
            name='imagetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Imagetype', verbose_name='Dorsal/Ventral'),
        ),
        migrations.AddField(
            model_name='frog',
            name='current_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Location', verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='frog',
            name='death',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Deathtype', verbose_name='Death'),
        ),
        migrations.AddField(
            model_name='frog',
            name='qen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Permit', verbose_name='QEN'),
        ),
        migrations.AddField(
            model_name='frog',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Species', verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='expt_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expt_location', to='frogs.Qap', verbose_name='Experiment Location'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='transferid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Transfer', verbose_name='Oocyte source'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Wastetype', verbose_name='Type of waste'),
        ),
    ]
