# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='experiment',
            name='disposal_sentby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frogs.Transporter', verbose_name='Disposal sent by'),
        ),
        migrations.AlterField(
            model_name='frog',
            name='death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frogs.Deathtype', verbose_name='Death'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Transporter', verbose_name='Transporter Name'),
        ),
    ]
