# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='tfr_date',
            new_name='transfer_date',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='tfr_from',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='tfr_to',
        ),
        migrations.AddField(
            model_name='frog',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='method',
            field=models.CharField(default='walked', max_length=120, verbose_name='Method'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frog',
            name='aec',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='AEC'),
        ),
        migrations.AlterField(
            model_name='frog',
            name='autoclave_date',
            field=models.DateField(blank=True, null=True, verbose_name='Autoclave Date'),
        ),
        migrations.AlterField(
            model_name='frog',
            name='autoclave_run',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Autoclave Run'),
        ),
        migrations.AlterField(
            model_name='frog',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Oocyte Health Condition'),
        ),
        migrations.AlterField(
            model_name='frog',
            name='death',
            field=models.CharField(blank=True, choices=[('culled', 'Culled'), ('found', 'Found dead'), ('alive', 'Not dead')], max_length=10, null=True, verbose_name='Type of Death'),
        ),
        migrations.AlterField(
            model_name='frog',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Death'),
        ),
        migrations.AlterField(
            model_name='frog',
            name='death_initials',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Initials'),
        ),
        migrations.AlterField(
            model_name='frog',
            name='frogid',
            field=models.CharField(max_length=30, unique=True, verbose_name='Frog ID'),
        ),
        migrations.AlterField(
            model_name='frog',
            name='incineration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Incineration Date'),
        ),
        migrations.AlterField(
            model_name='frog',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='General Remarks'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='aqis',
            field=models.CharField(max_length=20, verbose_name='AQIS'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='arrival_date',
            field=models.DateField(verbose_name='Arrival date'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='country',
            field=models.CharField(choices=[('usa', 'USA'), ('australia', 'Australia')], max_length=30, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='qen',
            field=models.CharField(max_length=20, unique=True, verbose_name='QEN'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='supplier',
            field=models.CharField(choices=[('nasco', 'NASCO'), ('xenopus', 'Xenopus One'), ('uq', 'UQ')], max_length=30, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='operationid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.Operation', verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transferapproval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogs.TransferApproval', verbose_name='Transfer from/to'),
        ),
        migrations.AlterField(
            model_name='transferapproval',
            name='tfr_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfr_from', to='frogs.Qap', verbose_name='Transfer from'),
        ),
        migrations.AlterField(
            model_name='transferapproval',
            name='tfr_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfr_to', to='frogs.Qap', verbose_name='Transfer to'),
        ),
    ]
