# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frogs', '0003_auto_20160420_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter',
            name='user',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='disposal_sentby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Disposal sent by'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporter', to=settings.AUTH_USER_MODEL, verbose_name='Transporter Name'),
        ),
        migrations.DeleteModel(
            name='Transporter',
        ),
    ]
