# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frogs', '0004_auto_20160420_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frogs.Wastetype', verbose_name='Type of waste'),
        ),
    ]
