# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogs', '0005_auto_20160420_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateField(verbose_name='Notes date')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('initials', models.CharField(blank=True, max_length=10, null=True, verbose_name='Initials')),
            ],
        ),
        migrations.AlterField(
            model_name='frog',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], max_length=10, verbose_name='Gender'),
        ),
    ]
