# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogs', '0007_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='report_contactdetails',
            field=models.CharField(default='Contact Details', max_length=1000),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='report_generalnotes',
            field=models.CharField(default='General Notes', max_length=1000),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='report_location',
            field=models.CharField(default='Location', max_length=1000),
        ),
    ]
