# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogs', '0009_auto_20160509_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Colour'),
        ),
    ]
