# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogs', '0010_permit_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='max_ops',
            field=models.SmallIntegerField(default=6, verbose_name='Max operations'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='op_interval',
            field=models.SmallIntegerField(default=6, verbose_name='Operation interval (mths)'),
        ),
    ]
